"use client";
import type { SupabaseClient } from "@supabase/supabase-js";
import { assertUuid, isUuid } from "@/lib/db/ids";
import { createSignedInRecord } from "@/lib/db/serverCreate";
import { mutateSignedInRecord } from "@/lib/db/serverMutate";
type Setter<T> = (value: T | ((current: T) => T)) => void;
export type InventoryRow = { id?: string; name: string; currentQty: number | null; targetQty: number | null; warning: boolean; workspaceId: string; autoGenerated?: boolean };
type DbItem = { id: string; workspace_id: string; name: string; current_qty: number | null; target_qty: number | null };
const dbToItem = (i: DbItem): InventoryRow => ({ id: i.id, workspaceId: i.workspace_id, name: i.name, currentQty: i.current_qty, targetQty: i.target_qty, warning: (i.current_qty ?? 0) < (i.target_qty ?? 0) });
export function createInventoryRepository({ isSignedIn, supabase, localItems, setLocalItems }: { isSignedIn: boolean; supabase: SupabaseClient | null; localItems: InventoryRow[]; setLocalItems: Setter<InventoryRow[]> }) {
  const useDb = isSignedIn && supabase;
  return {
    async getInventoryItems(workspaceId: string) {
      if (!useDb) return localItems.filter((i) => i.workspaceId === workspaceId);
      if (!isUuid(workspaceId)) return [];
      const { data, error } = await supabase.from("inventory_items").select("*").eq("workspace_id", workspaceId).order("name");
      if (error) throw new Error(error.message || "Unable to load inventory.");
      return ((data ?? []) as DbItem[]).map(dbToItem);
    },
    async createInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => [...c, item]), item;
      assertUuid(item.workspaceId, "Workspace");
      const data = await createSignedInRecord<DbItem>("inventory_item", { workspace_id: item.workspaceId, name: item.name, current_qty: item.currentQty, target_qty: item.targetQty });
      return dbToItem(data);
    },
    async updateInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => c.map((i) => i.workspaceId === item.workspaceId && i.name.toLowerCase() === item.name.toLowerCase() ? item : i)), item;
      assertUuid(item.workspaceId, "Workspace");
      const data = await mutateSignedInRecord<DbItem>("inventory_item", "update", {
        id: item.id,
        workspace_id: item.workspaceId,
        name: item.name,
        current_qty: item.currentQty,
        target_qty: item.targetQty,
      });
      if (!data) throw new Error("Unable to update inventory.");
      return dbToItem(data);
    },
    async deleteInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => c.filter((i) => !(i.workspaceId === item.workspaceId && i.name === item.name))), true;
      assertUuid(item.workspaceId, "Workspace");
      await mutateSignedInRecord<boolean>("inventory_item", "delete", {
        id: item.id,
        workspace_id: item.workspaceId,
        name: item.name,
      });
      return true;
    },
  };
}
