"use client";
import type { SupabaseClient } from "@supabase/supabase-js";
type Setter<T> = (value: T | ((current: T) => T)) => void;
export type InventoryRow = { id?: string; name: string; currentQty: number | null; targetQty: number | null; warning: boolean; workspaceId: string; autoGenerated?: boolean };
type DbItem = { id: string; workspace_id: string; name: string; current_qty: number | null; target_qty: number | null };
const dbToItem = (i: DbItem): InventoryRow => ({ id: i.id, workspaceId: i.workspace_id, name: i.name, currentQty: i.current_qty, targetQty: i.target_qty, warning: (i.current_qty ?? 0) < (i.target_qty ?? 0) });
export function createInventoryRepository({ isSignedIn, supabase, localItems, setLocalItems }: { isSignedIn: boolean; supabase: SupabaseClient | null; localItems: InventoryRow[]; setLocalItems: Setter<InventoryRow[]> }) {
  const useDb = isSignedIn && supabase;
  return {
    async getInventoryItems(workspaceId: string) {
      if (!useDb) return localItems.filter((i) => i.workspaceId === workspaceId);
      const { data, error } = await supabase.from("inventory_items").select("*").eq("workspace_id", workspaceId).order("name");
      if (error) throw new Error(error.message || "Unable to load inventory.");
      return ((data ?? []) as DbItem[]).map(dbToItem);
    },
    async createInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => [...c, item]), item;
      const { data, error } = await supabase.from("inventory_items").insert({ workspace_id: item.workspaceId, name: item.name, current_qty: item.currentQty, target_qty: item.targetQty }).select("*").single();
      if (error) throw new Error(error.message || "Unable to create inventory item.");
      return dbToItem(data as DbItem);
    },
    async updateInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => c.map((i) => i.workspaceId === item.workspaceId && i.name.toLowerCase() === item.name.toLowerCase() ? item : i)), item;
      const query = supabase.from("inventory_items").update({ name: item.name, current_qty: item.currentQty, target_qty: item.targetQty });
      const { data, error } = item.id ? await query.eq("id", item.id).select("*").single() : await query.eq("workspace_id", item.workspaceId).ilike("name", item.name).select("*").single();
      if (error) throw new Error(error.message || "Unable to update inventory.");
      return dbToItem(data as DbItem);
    },
    async deleteInventoryItem(item: InventoryRow) {
      if (!useDb) return setLocalItems((c) => c.filter((i) => !(i.workspaceId === item.workspaceId && i.name === item.name))), true;
      const query = supabase.from("inventory_items").delete();
      const { error } = item.id ? await query.eq("id", item.id) : await query.eq("workspace_id", item.workspaceId).eq("name", item.name);
      if (error) throw new Error(error.message || "Unable to delete inventory.");
      return true;
    },
  };
}
