export const clients = [
  // LANDSCAPING

  {
    id: "1",
    workspaceId: "landscaping",
    name: "Jones Family",
    status: "Active",
    balance: "$200",
    email: "jones@example.com",
    phone: "(555) 100-0001",
    address: "300 W Tienken Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48306",
  },
  {
    id: "2",
    workspaceId: "landscaping",
    name: "Brown Family",
    status: "Active",
    balance: "$350",
    email: "brown@example.com",
    phone: "(555) 100-0002",
    address: "1200 E Avon Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },
  {
    id: "3",
    workspaceId: "landscaping",
    name: "Acme HOA",
    status: "Active",
    balance: "$1500",
    email: "contact@acmehoa.com",
    phone: "(555) 100-0003",
    address: "900 Livernois Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },
  {
    id: "4",
    workspaceId: "landscaping",
    name: "John Smith",
    status: "Active",
    balance: "$450",
    email: "john@example.com",
    phone: "(555) 100-0004",
    address: "550 W Hamlin Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },
  {
    id: "5",
    workspaceId: "landscaping",
    name: "Sunset Apartments",
    status: "Active",
    balance: "$120",
    email: "office@sunsetapartments.com",
    phone: "(555) 100-0005",
    address: "1400 Walton Blvd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48309",
  },
  {
    id: "6",
    workspaceId: "landscaping",
    name: "Johnson Residence",
    status: "Active",
    balance: "$800",
    email: "johnson@example.com",
    phone: "(555) 100-0006",
    address: "1700 S Livernois Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },

  // SNOW REMOVAL

  {
    id: "7",
    workspaceId: "snow-removal",
    name: "Rochester Community Church",
    status: "Lead",
    balance: "$3500",
    email: "office@church.org",
    phone: "(555) 200-0001",
    address: "250 W Auburn Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },
  {
    id: "8",
    workspaceId: "snow-removal",
    name: "Riverside Office Park",
    status: "Active",
    balance: "$6800",
    email: "manager@riverside.com",
    phone: "(555) 200-0002",
    address: "400 Water St",
    city: "Rochester",
    state: "MI",
    zip: "48307",
  },
  {
    id: "9",
    workspaceId: "snow-removal",
    name: "Winter Ridge Condos",
    status: "Active",
    balance: "$9200",
    email: "hoa@winterridge.com",
    phone: "(555) 200-0003",
    address: "2200 Crooks Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48309",
  },
  {
    id: "10",
    workspaceId: "snow-removal",
    name: "Oakland Medical Center",
    status: "Active",
    balance: "$650",
    email: "facilities@oaklandmedical.com",
    phone: "(555) 200-0004",
    address: "1101 W University Dr",
    city: "Rochester",
    state: "MI",
    zip: "48307",
  },
  {
    id: "11",
    workspaceId: "snow-removal",
    name: "North Plaza",
    status: "Active",
    balance: "$2400",
    email: "management@northplaza.com",
    phone: "(555) 200-0005",
    address: "1900 S Rochester Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },

  // PROPERTIES

  {
    id: "12",
    workspaceId: "properties",
    name: "Maple Grove Apartments",
    status: "Active",
    balance: "$1200",
    email: "office@maplegrove.com",
    phone: "(555) 300-0001",
    address: "1000 Barclay Cir",
    city: "Rochester Hills",
    state: "MI",
    zip: "48307",
  },
  {
    id: "13",
    workspaceId: "properties",
    name: "Riverside Office Park",
    status: "Active",
    balance: "$950",
    email: "manager@riverside.com",
    phone: "(555) 300-0002",
    address: "400 Water St",
    city: "Rochester",
    state: "MI",
    zip: "48307",
  },
  {
    id: "14",
    workspaceId: "properties",
    name: "Sunset Strip Mall",
    status: "Active",
    balance: "$8500",
    email: "leasing@sunsetstripmall.com",
    phone: "(555) 300-0003",
    address: "1200 Walton Blvd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48309",
  },
  {
    id: "15",
    workspaceId: "properties",
    name: "Green Valley HOA",
    status: "Active",
    balance: "$2100",
    email: "board@greenvalleyhoa.com",
    phone: "(555) 300-0004",
    address: "800 E Tienken Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48306",
  },
  {
    id: "16",
    workspaceId: "properties",
    name: "Johnson Commercial",
    status: "Active",
    balance: "$4750",
    email: "admin@johnsoncommercial.com",
    phone: "(555) 300-0005",
    address: "2100 Crooks Rd",
    city: "Rochester Hills",
    state: "MI",
    zip: "48309",
  },
];