export const jobs = [
  // LANDSCAPING

  {
    id: "1",
    workspaceId: "landscaping",
    name: "Jones Residence",
    client: "Jones Family",
    status: "Lead",
    value: "$200",
    date: "2026-06-10",
  },
  {
    id: "2",
    workspaceId: "landscaping",
    name: "Brown Property",
    client: "Brown Family",
    status: "Lead",
    value: "$350",
    date: "2026-06-12",
  },
  {
    id: "3",
    workspaceId: "landscaping",
    name: "Acme HOA Cleanup",
    client: "Acme HOA",
    status: "Quoted",
    value: "$1,500",
    date: "2026-06-14",
  },
  {
    id: "4",
    workspaceId: "landscaping",
    name: "Spring Cleanup",
    client: "John Smith",
    status: "Scheduled",
    value: "$450",
    date: "2026-06-15",
  },
  {
    id: "5",
    workspaceId: "landscaping",
    name: "Weekly Service",
    client: "Sunset Apartments",
    status: "Completed",
    value: "$120",
    date: "2026-06-18",
  },
  {
    id: "6",
    workspaceId: "landscaping",
    name: "Mulch Installation",
    client: "Johnson Residence",
    status: "Paid",
    value: "$800",
    date: "2026-06-17",
  },

  // SNOW REMOVAL

  {
    id: "7",
    workspaceId: "snow-removal",
    name: "Church Snow Contract",
    client: "Rochester Community Church",
    status: "Lead",
    value: "$3,500",
    date: "2026-11-01",
  },
  {
    id: "8",
    workspaceId: "snow-removal",
    name: "Office Lot Bid",
    client: "Riverside Office Park",
    status: "Quoted",
    value: "$6,800",
    date: "2026-11-05",
  },
  {
    id: "9",
    workspaceId: "snow-removal",
    name: "Condo Association",
    client: "Winter Ridge Condos",
    status: "Scheduled",
    value: "$9,200",
    date: "2026-11-10",
  },
  {
    id: "10",
    workspaceId: "snow-removal",
    name: "Emergency Salt Run",
    client: "Oakland Medical Center",
    status: "Completed",
    value: "$650",
    date: "2026-11-12",
  },
  {
    id: "11",
    workspaceId: "snow-removal",
    name: "Retail Plaza Clearing",
    client: "North Plaza",
    status: "Paid",
    value: "$2,400",
    date: "2026-11-15",
  },

  // PROPERTIES

  {
    id: "12",
    workspaceId: "properties",
    name: "Unit 204 Turnover",
    client: "Maple Grove Apartments",
    status: "Lead",
    value: "$1,200",
    date: "2026-07-01",
  },
  {
    id: "13",
    workspaceId: "properties",
    name: "HVAC Inspection",
    client: "Riverside Office Park",
    status: "Quoted",
    value: "$950",
    date: "2026-07-03",
  },
  {
    id: "14",
    workspaceId: "properties",
    name: "Parking Lot Sealcoat",
    client: "Sunset Strip Mall",
    status: "Scheduled",
    value: "$8,500",
    date: "2026-07-10",
  },
  {
    id: "15",
    workspaceId: "properties",
    name: "Roof Leak Repair",
    client: "Green Valley HOA",
    status: "Completed",
    value: "$2,100",
    date: "2026-07-12",
  },
  {
    id: "16",
    workspaceId: "properties",
    name: "Quarterly Maintenance",
    client: "Johnson Commercial",
    status: "Paid",
    value: "$4,750",
    date: "2026-07-15",
  },
];