export const defaultBusinessTypes = [
  "Landscaping",
  "Lawn Care",
  "Snow Removal",
  "Pressure Washing",
  "Painting",
  "Roofing",
  "Plumbing",
  "Electrical",
  "HVAC",
  "Handyman",
  "Carpentry",
  "Concrete",
  "Masonry",
  "Fencing",
  "Tree Service",
  "Excavation",
  "Septic",
  "Pest Control",
  "Cleaning",
  "Janitorial",
  "Property Maintenance",
  "Property Management",
  "Auto Detailing",
  "Mobile Mechanic",
  "Welding",
  "Millwright",
  "Flooring",
  "Drywall",
  "Insulation",
  "Garage Door",
  "Pool Service",
  "Irrigation",
  "Window Cleaning",
  "Moving",
  "Junk Removal",
  "Other",
] as const;
