"use client";

import type { SupabaseClient } from "@supabase/supabase-js";

import { readStoredJson, storageKeys } from "@/lib/clientStorage";
import type { ClientRow } from "@/lib/clientTypes";
import { createClientsRepository } from "@/lib/db/clients";
import { createCalendarEventsRepository } from "@/lib/db/calendarEvents";
import { createDocumentsRepository } from "@/lib/db/documents";
import { createExpensesRepository, type ExpenseRow } from "@/lib/db/expenses";
import { createInventoryRepository, type InventoryRow } from "@/lib/db/inventory";
import { createInvoicesRepository } from "@/lib/db/invoices";
import { createJobsRepository } from "@/lib/db/jobs";
import type { StoredDocument } from "@/lib/db/documents";
import type { ClientCalendarEvent } from "@/lib/db/calendarEvents";
import type { InvoiceRow } from "@/lib/frontierInvoices";
import type { Job } from "@/lib/jobTypes";
import type { LocalImportCounts, LocalImportSummary } from "@/lib/migration/localImportTypes";

function norm(value: string | undefined) {
  return (value ?? "").trim().toLowerCase();
}

export function previewLocalFrontierData(workspaceId: string): LocalImportCounts {
  const clients = readStoredJson<ClientRow[]>(storageKeys.clients, []).filter((x) => x.workspaceId === workspaceId);
  const jobs = readStoredJson<Job[]>(storageKeys.jobs, []).filter((x) => x.workspaceId === workspaceId);
  const invoices = readStoredJson<InvoiceRow[]>(storageKeys.invoices, []).filter((x) => x.workspaceId === workspaceId);
  const expenses = readStoredJson<ExpenseRow[]>(storageKeys.expenses, []).filter((x) => x.workspaceId === workspaceId);
  const inventory = readStoredJson<InventoryRow[]>(storageKeys.inventory, []).filter((x) => x.workspaceId === workspaceId && !x.autoGenerated);
  const events = readStoredJson<ClientCalendarEvent[]>(storageKeys.clientCalendarEvents, []).filter((x) => x.workspaceId === workspaceId);
  const documents = readStoredJson<StoredDocument[]>(storageKeys.documents, []).filter((x) => x.workspaceId === workspaceId);
  const settings = readStoredJson<{ workspaceId: string }[]>(storageKeys.settings, []).filter((x) => x.workspaceId === workspaceId);

  return {
    clients: clients.length,
    jobs: jobs.length,
    jobMaterials: jobs.reduce((total, job) => total + (job.materials?.length ?? 0), 0),
    invoices: invoices.length,
    invoiceLineItems: invoices.reduce((total, invoice) => total + (invoice.lineItems?.length ?? 0), 0),
    expenses: expenses.length,
    inventory: inventory.length,
    clientCalendarEvents: events.length,
    documents: documents.length,
    routes: 0,
    workspaceSettings: settings.length,
  };
}

export async function importLocalFrontierData({
  workspaceId,
  supabase,
}: {
  workspaceId: string;
  supabase: SupabaseClient;
}): Promise<LocalImportSummary> {
  const summary: LocalImportSummary = { created: 0, skipped: 0, failed: 0, warnings: [] };
  const noop = () => undefined;
  const clientsRepo = createClientsRepository({ isSignedIn: true, supabase, localClients: [], setLocalClients: noop });
  const jobsRepo = createJobsRepository({ isSignedIn: true, supabase, localJobs: [], setLocalJobs: noop });
  const invoicesRepo = createInvoicesRepository({ isSignedIn: true, supabase, localInvoices: [], setLocalInvoices: noop });
  const expensesRepo = createExpensesRepository({ isSignedIn: true, supabase, localExpenses: [], setLocalExpenses: noop });
  const inventoryRepo = createInventoryRepository({ isSignedIn: true, supabase, localItems: [], setLocalItems: noop });
  const eventsRepo = createCalendarEventsRepository({ isSignedIn: true, supabase, localEvents: [], setLocalEvents: noop });
  const documentsRepo = createDocumentsRepository({ isSignedIn: true, supabase, localDocuments: [], setLocalDocuments: noop });

  const localClients = readStoredJson<ClientRow[]>(storageKeys.clients, []).filter((x) => x.workspaceId === workspaceId);
  const localJobs = readStoredJson<Job[]>(storageKeys.jobs, []).filter((x) => x.workspaceId === workspaceId);
  const localInvoices = readStoredJson<InvoiceRow[]>(storageKeys.invoices, []).filter((x) => x.workspaceId === workspaceId);
  const localExpenses = readStoredJson<ExpenseRow[]>(storageKeys.expenses, []).filter((x) => x.workspaceId === workspaceId);
  const localInventory = readStoredJson<InventoryRow[]>(storageKeys.inventory, []).filter((x) => x.workspaceId === workspaceId && !x.autoGenerated);
  const localEvents = readStoredJson<ClientCalendarEvent[]>(storageKeys.clientCalendarEvents, []).filter((x) => x.workspaceId === workspaceId);
  const localDocuments = readStoredJson<StoredDocument[]>(storageKeys.documents, []).filter((x) => x.workspaceId === workspaceId);

  const existingClients = await clientsRepo.getClients(workspaceId);
  const clientIdMap = new Map<string, string>();
  for (const client of localClients) {
    const duplicate = existingClients.find((x) => norm(x.name) === norm(client.name));
    if (duplicate) {
      clientIdMap.set(client.id, duplicate.id);
      summary.skipped++;
      continue;
    }
    const created = await clientsRepo.createClient({ ...client, workspaceId });
    if (created) {
      existingClients.push(created);
      clientIdMap.set(client.id, created.id);
      summary.created++;
    } else summary.failed++;
  }

  const existingJobs = await jobsRepo.getJobs(workspaceId);
  const jobIdMap = new Map<string, string>();
  for (const job of localJobs) {
    const nextClientId = job.clientId ? clientIdMap.get(job.clientId) ?? job.clientId : undefined;
    const duplicate = existingJobs.find((x) => norm(x.name) === norm(job.name) && x.date === job.date && (x.clientId ?? "") === (nextClientId ?? ""));
    if (duplicate) {
      jobIdMap.set(job.id, duplicate.id);
      summary.skipped++;
      continue;
    }
    const created = await jobsRepo.createJob({ ...job, workspaceId, clientId: nextClientId });
    if (created) {
      existingJobs.push(created);
      jobIdMap.set(job.id, created.id);
      summary.created++;
    } else summary.failed++;
  }

  const existingInvoices = await invoicesRepo.getInvoices(workspaceId);
  for (const invoice of localInvoices) {
    if (existingInvoices.some((x) => x.invoiceNumber === invoice.invoiceNumber)) {
      summary.skipped++;
      continue;
    }
    const created = await invoicesRepo.createInvoice({
      ...invoice,
      workspaceId,
      sourceClientId: invoice.sourceClientId ? clientIdMap.get(invoice.sourceClientId) ?? invoice.sourceClientId : undefined,
      jobId: invoice.jobId ? jobIdMap.get(invoice.jobId) ?? invoice.jobId : undefined,
    });
    if (created) summary.created++;
    else summary.failed++;
  }

  const existingInventory = await inventoryRepo.getInventoryItems(workspaceId);
  for (const item of localInventory) {
    if (existingInventory.some((x) => norm(x.name) === norm(item.name))) {
      summary.skipped++;
      continue;
    }
    const created = await inventoryRepo.createInventoryItem({ ...item, workspaceId });
    if (created) summary.created++;
    else summary.failed++;
  }

  const existingExpenses = await expensesRepo.getExpenses(workspaceId);
  for (const expense of localExpenses) {
    if (existingExpenses.some((x) => norm(x.description) === norm(expense.description) && x.amount === expense.amount && x.category === expense.category)) {
      summary.skipped++;
      continue;
    }
    const created = await expensesRepo.createExpense({ ...expense, workspaceId });
    if (created) summary.created++;
    else summary.failed++;
  }

  const existingEvents = await eventsRepo.getEvents(workspaceId);
  for (const event of localEvents) {
    const nextClientId = event.clientId ? clientIdMap.get(event.clientId) ?? event.clientId : "";
    if (existingEvents.some((x) => norm(x.title) === norm(event.title) && x.date === event.date && x.clientId === nextClientId)) {
      summary.skipped++;
      continue;
    }
    const created = await eventsRepo.createEvent({ ...event, workspaceId, clientId: nextClientId });
    if (created) summary.created++;
    else summary.failed++;
  }

  const existingDocs = await documentsRepo.getDocuments(workspaceId);
  for (const doc of localDocuments) {
    if (existingDocs.some((x) => norm(x.name) === norm(doc.name) && x.fileName === doc.fileName && x.createdAt === doc.createdAt)) {
      summary.skipped++;
      continue;
    }
    const created = await documentsRepo.createDocument({
      ...doc,
      workspaceId,
      clientId: doc.clientId ? clientIdMap.get(doc.clientId) ?? doc.clientId : "",
      jobId: doc.jobId ? jobIdMap.get(doc.jobId) ?? doc.jobId : "",
    });
    if (created) summary.created++;
    else summary.failed++;
  }

  summary.warnings.push("Local data was not deleted.");
  return summary;
}
