"use client";

import { useEffect, useState } from "react";

import { useWorkspace } from "@/components/WorkspaceContext";
import { inventory as defaultInventory } from "@/lib/inventory";
import { jobs as defaultJobs } from "@/lib/jobs";

type InventoryRow = {
  name: string;
  currentQty: number | null;
  targetQty: number | null;
  warning: boolean;
  workspaceId: string;
  autoGenerated?: boolean;
};

export default function InventoryPage() {
  const { activeWorkspace } = useWorkspace();

  const [inventoryItems, setInventoryItems] = useState<InventoryRow[]>(
    defaultInventory
  );
  const [jobItems, setJobItems] = useState(defaultJobs);
  const [selectedItems, setSelectedItems] = useState<string[]>([]);

  const [newItemOpen, setNewItemOpen] = useState(false);
  const [itemName, setItemName] = useState("");
  const [currentQty, setCurrentQty] = useState("");
  const [targetQty, setTargetQty] = useState("");

  useEffect(() => {
    const savedJobs = localStorage.getItem("frontier-jobs");

    if (savedJobs) {
      try {
        setJobItems(JSON.parse(savedJobs));
      } catch {
        setJobItems(defaultJobs);
      }
    }
  }, []);

  const workspaceInventory = inventoryItems.filter(
    (item) => item.workspaceId === activeWorkspace.id
  );

  const activeMaterialJobs = jobItems.filter(
    (job) =>
      job.workspaceId === activeWorkspace.id &&
      (job.status === "Scheduled" || job.status === "Completed")
  );

  const autoMaterialRows: InventoryRow[] = activeMaterialJobs
    .flatMap((job) =>
      job.materials.map((material) => ({
        name: material.name.trim(),
        currentQty: null,
        targetQty: null,
        warning: true,
        workspaceId: activeWorkspace.id,
        autoGenerated: true,
      }))
    )
    .filter((material, index, materials) => {
      const normalizedName = material.name.toLowerCase();

      return (
        material.name.length > 0 &&
        materials.findIndex(
          (candidate) => candidate.name.toLowerCase() === normalizedName
        ) === index
      );
    });

  const mergedInventory = [
    ...workspaceInventory,
    ...autoMaterialRows.filter(
      (material) =>
        !workspaceInventory.some(
          (item) =>
            item.name.trim().toLowerCase() === material.name.trim().toLowerCase()
        )
    ),
  ];

  function getReservedForItem(itemName: string) {
    return activeMaterialJobs.flatMap((job) =>
      job.materials
        .filter(
          (material) =>
            material.name.trim().toLowerCase() === itemName.trim().toLowerCase()
        )
        .map((material) => ({
          jobId: job.id,
          jobName: job.name,
          jobStatus: job.status,
          quantity: material.quantity,
        }))
    );
  }

  function toggleItem(itemName: string) {
    setSelectedItems((current) =>
      current.includes(itemName)
        ? current.filter((name) => name !== itemName)
        : [...current, itemName]
    );
  }

  function removeSelectedItems() {
    setInventoryItems((current) =>
      current.filter((item) => !selectedItems.includes(item.name))
    );

    setSelectedItems([]);
  }

  function resetNewItemForm() {
    setItemName("");
    setCurrentQty("");
    setTargetQty("");
  }

  function closeNewItemModal() {
    setNewItemOpen(false);
    resetNewItemForm();
  }

  function addInventoryItem() {
    if (!itemName.trim()) return;

    const current = Number(currentQty);
    const target = Number(targetQty);

    if (Number.isNaN(current) || Number.isNaN(target)) return;

    setInventoryItems((existing) => [
      ...existing,
      {
        name: itemName.trim(),
        currentQty: current,
        targetQty: target,
        warning: current < target,
        workspaceId: activeWorkspace.id,
      },
    ]);

    closeNewItemModal();
  }

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">


        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setNewItemOpen(true)}
            className="rounded-lg bg-blue-600 px-4 py-2 text-white shadow hover:bg-blue-700"
          >
            + Add Item
          </button>

          <button
            type="button"
            onClick={removeSelectedItems}
            disabled={selectedItems.length === 0}
            className="rounded-lg bg-red-600 px-4 py-2 text-white shadow hover:bg-red-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Remove Item
          </button>
        </div>
      </div>

      <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-200">
        Inventory demand is calculated only from{" "}
        <strong>Scheduled</strong> and <strong>Completed</strong> jobs. Lead,
        Quoted, and Paid jobs do not reserve inventory. Materials from jobs will
        auto-appear even if no inventory item exists yet.
      </div>

      {selectedItems.length > 0 && (
        <div className="rounded-xl bg-gray-900 p-4 text-white">
          {selectedItems.length} item
          {selectedItems.length !== 1 ? "s" : ""} selected
        </div>
      )}

      {newItemOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4">
          <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl dark:bg-gray-900">
            <div className="mb-6 flex items-center justify-between">
              <h2 className="text-xl font-bold text-gray-950 dark:text-gray-100">
                Add Inventory Item
              </h2>

              <button
                type="button"
                onClick={closeNewItemModal}
                className="text-2xl text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
              >
                ×
              </button>
            </div>

            <div className="space-y-4">
              <input
                type="text"
                value={itemName}
                onChange={(event) => setItemName(event.target.value)}
                placeholder="Item Name"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 dark:border-gray-700 dark:bg-gray-800"
              />

              <input
                type="number"
                value={currentQty}
                onChange={(event) => setCurrentQty(event.target.value)}
                placeholder="Current Quantity"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 dark:border-gray-700 dark:bg-gray-800"
              />

              <input
                type="number"
                value={targetQty}
                onChange={(event) => setTargetQty(event.target.value)}
                placeholder="Target Quantity"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 dark:border-gray-700 dark:bg-gray-800"
              />

              <button
                type="button"
                onClick={addInventoryItem}
                className="w-full rounded-lg bg-blue-600 py-3 text-white hover:bg-blue-700"
              >
                Add Item
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="overflow-x-auto rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-gray-900">
        <table className="min-w-[1100px] w-full">
          <thead>
            <tr className="border-b border-gray-200 bg-white text-sm uppercase tracking-wide text-gray-500 dark:border-gray-800 dark:bg-gray-900 dark:text-gray-400">
              <th className="w-12 px-4 py-4"></th>
              <th className="px-6 py-4 text-left">Item Name</th>
              <th className="px-6 py-4 text-center">Current Qty</th>
              <th className="px-6 py-4 text-center">Reserved</th>
              <th className="px-6 py-4 text-center">Available</th>
              <th className="px-6 py-4 text-center">Target Qty</th>
              <th className="px-6 py-4 text-left">Tied Jobs</th>
              <th className="px-6 py-4 text-right">Suggested Order</th>
            </tr>
          </thead>

          <tbody>
            {mergedInventory.length > 0 ? (
              mergedInventory.map((item) => {
                const reservedJobs = getReservedForItem(item.name);

                const reservedQty = reservedJobs.reduce(
                  (total, reserved) => total + reserved.quantity,
                  0
                );

                const availableAfterJobs =
                  item.currentQty === null ? null : item.currentQty - reservedQty;

                const suggestedOrder =
                  item.targetQty === null || availableAfterJobs === null
                    ? null
                    : Math.max(item.targetQty - availableAfterJobs, 0);

                const warning =
                  item.currentQty === null ||
                  item.targetQty === null ||
                  (availableAfterJobs !== null &&
                    availableAfterJobs < item.targetQty);

                return (
                  <tr
                    key={`${item.workspaceId}-${item.name}`}
                    className="border-b border-gray-200 text-base last:border-b-0 dark:border-gray-800 lg:text-lg"
                  >
                    <td className="px-4 py-5 text-center">
                      <input
                        type="checkbox"
                        checked={selectedItems.includes(item.name)}
                        onChange={() => toggleItem(item.name)}
                        disabled={item.autoGenerated}
                        className="h-4 w-4 disabled:cursor-not-allowed disabled:opacity-40"
                        title={
                          item.autoGenerated
                            ? "Auto-generated from job materials"
                            : undefined
                        }
                      />
                    </td>

                    <td className="px-6 py-5 font-medium text-gray-950 dark:text-gray-100">
                      <div className="flex items-center gap-3">
                        {warning && (
                          <span className="text-orange-500">⚠</span>
                        )}

                        <span>{item.name}</span>

                        {item.autoGenerated && (
                          <span className="rounded-full bg-blue-100 px-2 py-1 text-xs font-medium text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
                            Job material
                          </span>
                        )}
                      </div>
                    </td>

                    <td className="px-6 py-5 text-center text-gray-900 dark:text-gray-100">
                      {item.currentQty ?? "—"}
                    </td>

                    <td className="px-6 py-5 text-center text-blue-600 dark:text-blue-400">
                      {reservedQty}
                    </td>

                    <td
                      className={`px-6 py-5 text-center ${
                        warning
                          ? "text-red-600 dark:text-red-400"
                          : "text-green-600 dark:text-green-400"
                      }`}
                    >
                      {availableAfterJobs ?? "—"}
                    </td>

                    <td className="px-6 py-5 text-center text-gray-500 dark:text-gray-400">
                      {item.targetQty ?? "—"}
                    </td>

                    <td className="px-6 py-5 text-sm text-gray-600 dark:text-gray-400">
                      {reservedJobs.length > 0 ? (
                        <div className="space-y-1">
                          {reservedJobs.map((reserved) => (
                            <div key={`${reserved.jobId}-${reserved.quantity}`}>
                              {reserved.quantity} → {reserved.jobName} (
                              {reserved.jobStatus})
                            </div>
                          ))}
                        </div>
                      ) : (
                        "—"
                      )}
                    </td>

                    <td
                      className={`px-6 py-5 text-right ${
                        warning
                          ? "text-orange-600 dark:text-orange-400"
                          : "text-green-600 dark:text-green-400"
                      }`}
                    >
                      {suggestedOrder ?? "—"}
                    </td>
                  </tr>
                );
              })
            ) : (
              <tr>
                <td
                  colSpan={8}
                  className="px-6 py-16 text-center text-xl text-gray-500 dark:text-gray-400"
                >
                  No inventory items or scheduled job materials for{" "}
                  {activeWorkspace.name}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
